spring.application.name=limits-service
#We added a client dependency for limit service , but spring cloud config servr is not ready
#So we have to make pring cloud config servr optional
spring.config.import=optional:configserver:http://localhost:8888

limits-service.minimum=2
limits-service.maximum=998
