spring.application.name=limits-service
#We added a client dependency for limit service , but spring cloud config servr is not ready
#So we have to make pring cloud config servr optional
spring.config.import=optional:configserver:http://localhost:8888

#changing this to see if we get the right reponse
limits-service.minimum=3
limits-service.maximum=996

spring.profiles.active=dev
spring.cloud.config.dev=dev
#you can set other properties also, like if you dont want the name limits-service.properties then:
#spring.cloud.config.name=golibaje